### ISSUE TITLE
[Partially solved; useful info to sticky] iscab.exe plugin - where to find?

### ISSUE THREAD

**Issue by Darthagnon** [Bioruebe/UniExtract2#119]
I've been trying to install all the plugins, but haven't had much luck so far with "iscab.exe" and "istools.dll". iscab is apparently an InstallShield thing, for which the latest versions of installshield have dropped support (to my chagrin, after I tried installing a trial of InstallShield to grab the files) (Source: https://community.flexerasoftware.com/showthread.php?222828-InstallShield-2016-ISCab-exe-Issues) - not that it's not still useful ;)

In my research, I've managed to find an "improved" version of iscab, that bypasses password requirements for InstallShield CABs at http://www.lifeasbob.com/2009/07/21/OpenAnInstallshieldCabFile.aspx (Ctrl+F page for "iscab.zip")
I also obtained istools.dll from http://www.dlldownloader.com/istools-dll/ (Can't tell if it's legit or not; looks better than some other dodgy sources I looked through)

Reckon these files will work? Would it be worth adding links to them into UniExtract? Notably, to the improved version of iscab?

Live long and prosper!

EDIT: I found an old UniExtract Google Code repo (https://code.google.com/archive/p/uniextract/source/default/source)  (via https://superuser.com/questions/88645/how-do-i-extract-an-installshield-cabinet-file) that includes all the required iscab and istools files in the source (just download the source zip and Ctrl+F to find the filenames "iscab.exe" and "istools.dll"). This may be the definitive version - should I use this version of iscab.exe, though, since the other claims to bypass password requirements?

**Comment by Darthagnon** [comment]
lifeasbob's page I linked also contains a whole load of other misc. extractors, etc. - not sure if they're included with uniextract or not, or if they're deprecated.

**Comment by HapaxOromenon** [comment]
The "improved" version may or may not be compatible with UniExtract. The other extractors on the page you linked to are programs like i5comp, i6comp, and E_WISE, all of which have been part of UniExtract from the beginning, but nowadays aren't used much, since InstallShield Versions 5 and 6 were mainly used in the mid-2000s, and reached end-of-life in 2008/9; similarly WISE Installer was acquired by Symantec (the same company that makes Norton Antivirus) in 2007, retired from general availability in 2010, and finally end-of-lifed in 2013. Most program installers these days use either Inno Setup or NSIS (for freeware and open-source software) or modern versions of InstallShield (for commercial software). These are extracted, of course, by innounp, 7-Zip, and unshield (or in some cases IsXunpack), respectively.

**Comment by ljcool2006** [comment]
Which download link should I pick?

**Comment by HapaxOromenon** [comment]
> Which download link should I pick?
If you really want to use iscab.exe, it looks like there's a working version at https://dl.dropboxusercontent.com/s/juxy8fc79ccfqra/InstallShield_Cabinet_File_Viewer.zip (linked from https://www.eevblog.com/forum/testgear/lost-flukeview-forms-software/). But it's really unnecessary given that UniExtract already uses unshield ( (https://github.com/twogood/unshield), an actively-maintained open source project that continues to support all modern versions of InstallShield.
