### ISSUE TITLE
StuffIt Expander changes file associations in registry when run

### ISSUE THREAD

**Issue by TheGuyInShades** [Bioruebe/UniExtract2#120]
When you run the StuffIt Expander it changes quite a few file associations to either "StuffItArchive" or "StuffItEncoded" and changes the Content Type to "application/x-stuffit", it doesn't actually create StuffItArchive or StuffItEncode keys though, so those filetypes can't be opened until they're file associations are changed back. It doesn't change the UserChoice key in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts at least, but it's still annoying. Is there some way to hack Expander.exe so it stops doing that?

**Comment by whitten** [comment]
I expect it can be resolved in the code.
To make it easier to get done, please use Registry Editor (whatever version you need) to extract the file associations that UniExtract needs to work, and the file extractions that Stuffit Expander leaves in place after it runs.  You can attach your two ".reg" files to your reply to this open issue.

**Comment by TheGuyInShades** [comment]
I don't know what you mean by file associations that UniExtract needs to work, I just run it from a desktop shortcut. I really don't want to run StuffIt Expander again, because then I'll have to fix all the file associations again. Maybe you could try it? Just double-clicking on the program in the bin folder of UniExtract will write the registry entries.

**Comment by Bioruebe** [comment]
Hmm, the whole Stuffit extraction is completely untouched code from original UniExtract. Maybe that's why is remained unnoticed for so long. Well, I agree that file associations shouldn't be changed by simply starting the extractor.

A workaround as suggested by @whitten should be possible, but I plan on replacing Stuffit Expander anyway (because of #117), so this problem may solve itself soon :)
