### ISSUE TITLE
WebP corruption with .Vis extraction

### ISSUE THREAD

**Issue by MissPervet** [Bioruebe/UniExtract2#145]
Hello, just wanted to know if this is a known issue or not. Seems every .Vis file that gets extracted, any WebP files get corrupted and can't be displayed. When I look in the log file, it finds the key just fine and even PNG images get displayed perfectly. Just wondering if there could be a fix or if it has to do with the limitations of the Vis extractor program.

I also verified that I can indeed see WebP images, I've installed the codecs to allow it. I've also plopped the images in Chrome where they're supported and only the extracted ones don't load.

Thanks for the program, it's great.

**Comment by Bioruebe** [comment]
The [info page](https://oezmen.eu/gameresources/) for the extractor only lists a few specific games as supported, everything else is pretty much 'might or might not work'.

I tested some archives from Deponia 3 and these WebP's display fine (as expected, because it is supported by vis3ext). I also encountered some broken ones in the past - just like you described: WebP files corrupt, other images work fine - but I didn't look any further into the issue back then.

So to answer your question, it's a limitation of the extractor. Unless there's an update or a different extractor (which works better), I don't see an easy fix.
