### ISSUE TITLE
Virus checker

### ISSUE THREAD

**Issue by harryray33** [Bioruebe/UniExtract2#158]
Thanks for the nightly update link....

I downloaded the nightly update and I ran it through virustotal and I got 5 virus alerts. I'm not too bothered as I've been using Uniextract for a while with no problem but I was wondering why I got the alerts?

I suppose I could run each file individually through virustotal to see where the problem is but I'm not sure I have the patience!! :0)

Also, I noticed that there is a file called acefile.exe...Isn't there a security problem with ace?

Thanks.

**Comment by vatterspun** [comment]
Virustotal is a collection of different virus programs, some more paranoid than others.  Generally speaking, if one of these companies is not sure, they'll label something as bad because they don't want you switching to another AV option if you get malware.  As such, we label good programs that are bad as "false positives" and should over the coming weeks show up as benign.

Freeware developer Nirsoft has had this up since before VirusTotal existed, but it's still instructive: https://nirsoft.net/false_positive_report.html

**Comment by Bioruebe** [comment]
Additionally, it is very hard to 'convince' anti-malware programs that a software is harmless. There is no standard way to report false positives and even if one exists, it is likely that after an update (of the software *or* the AV) the file gets misdetected again.

> I could run each file individually through virustotal [...] but I'm not sure I have the patience

That's exactly the problem! Making sure that every AV software considers UniExtract *and all* of its helper programs safe is an incredible amount of work. I prefer to ensure the most common AVs don't detect UniExtract and that's it.

> Isn't there a security problem with ace?

There was a security issue regarding extraction of `.ace` files in Winrar (and some other programs). `acefile` is not affected.
