### ISSUE TITLE
Cannot extract Edge (Chromium) MSI

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Bioruebe/UniExtract2#219]
Example:
https://chocolatey.org/packages/microsoft-edge-insider-dev/86.0.615.3

Direct link:
http://dl.delivery.mp.microsoft.com/filestreamingservice/files/758647be-f560-49da-91b7-263d39309295/MicrosoftEdgeDevEnterpriseX64.msi

Tried all four ways of MSI extraction.

**Comment by HapaxOromenon** [comment]
Examining the MSI file with SuperOrca shows that it doesn't contain any files packed in the usual way, but rather some binary data together with custom actions. Using 7-Zip, or MsiX (the 2nd of the 4 ways), or SuperOrca to extract the binary data yields a file called "Binary.MicrosoftEdgeDevInstaller", which can be renamed to .exe.

This exe file appears to be in a custom format that is not readily extractable. If you try 7-Zip on it, you get a file called "102~", which turns out to be some kind of weird modified TAR archive that shows as corrupted if you try to extract it normally. The best I could do was use cpio (http://gnuwin32.sourceforge.net/packages/cpio.htm), which can get some data out of corrupted TAR archives by skipping the unreadable data. In this way I was able to extract about 4.5 MB of readable files out of the 95 MB "102~" file, which clearly is far from everything.

At the moment it doesn't seem possible to go any further - at least, not without trying to decipher the format of the Binary.MicrosoftEdgeDevInstaller exe file. Perhaps someone who has reverse-engineering knowledge and access to tools like IDA could take a look, but I wouldn't get your hopes up.

**Comment by stdin82** [comment]
@HapaxOromenon It's the same as Chrome standalone installer, can be extracted, but not easy
https://support.google.com/chrome/a/forum/AAAARjBu3mECpKAW6mShmw/?hl=en

**Comment by Bioruebe** [comment]
Thanks for providing such detailed information about the installer format. But even with the step-by-step from the Chrome help page, it's just too complex to extract. I don't see a way to add this functionality to UniExtract, sorry.

**Comment by sergeevabc** [comment]
[PorEdgeUpd](https://github.com/UndertakerBen/PorEdgeUpd) uses some technique to extract Edge (Chrome-based) MSI installers and it works.

**Comment by sunrenjie** [comment]
Here is an indirect way (example: "Microsoft Edge-Stable Channel" 111.0.1661.43 x64).

Run the MicrosoftEdgeInstaller.exe (extracted from MSI and renamed; see above comment), it will extract the program folder (something like EU901.tmp) to some prefix temp folder.
* The prefix temp folder can be %temp% or `C:\Program Files (x86)\Microsoft\Temp`. Use Procmon64.exe to figure it out.
* Depending on the current environment, it may succeed or fail.
* If it succeeds (unfortunately), it will remove the temp folder. We might copy out the installed program folder, uninstall it, and leave.
  * Alternatively, heavily load the system to make it slower.
* If it fails, it gives a warning prompt with the temp folder kept as is, and we will have enough time to respond.
  * It fails typically when the installer finds out it's outdated. Run a later version once, or keep the Internet connected, to allow it do the job.
  * If we've disabled edge auto-update by replacing the folder with an empty file, the installation may fail.
* Be quick, copy out the temp folder.

Note the file named `MicrosoftEdge_X64_111.0.1661.43.exe.{0D50BFEC-CD6A-4F9A-964C-C7416E3ACB10}`, which can now be extracted by 7zFM.

**Comment by bananakid** [comment]
> [@HapaxOromenon](https://github.com/HapaxOromenon) It's the same as Chrome standalone installer, can be extracted, but not easy https://support.google.com/chrome/a/forum/AAAARjBu3mECpKAW6mShmw/?hl=en

Does anyone have a saved copy by chance?

@sunrenjie, yep, that's how I've been extracting it for a while…
