### ISSUE TITLE
Virus/Trojan

### ISSUE THREAD

**Issue by zedd-0** [Bioruebe/UniExtract2#228]
since version v2.0.0 RC2 after 2019-03-13 via updater, till now, v2.0.0 RC4 2020-09-23.
all versions of "UniExtract.exe" are detected as an Trojan.

the old v2.0.0 RC2 2019-03-13 does not have this error.

https://ibb.co/fX8jnR2
alert level: serious/massive

maybe it is a false positive:
https://www.virustotal.com/gui/file/82e9fccdb0fd4e6b6a7d7ccf4113018d1e962405340c16f394752e2ab2843f76

please fix your app or talk to the antivirus manufacturers.

i will not stop using "Windows 10 defender 2004" or:
- McAfee-GW-Edition
- SecureAge APEX
- Cyren
- Bkav

thanks.

**Comment by zedd-0** [comment]
the current version (via updater) is blocked again.
and defender is broken, i cannot set it on a white list.

**Comment by 4B4DB4B3** [comment]
> i will not stop using "Windows 10 defender 2004"
Use x64dbg or IDA Pro to sure what this not virus.
I using UniExtract a year, and I can say that there are no viruses here

**Comment by zedd-0** [comment]
i KNOW this is not a virus.
but defender & Co. think so.
and you are not alone with the problem.
It is just too quickly judged, that scripting programs are preventive all viruses.

I just kindly ask you to test it beforehand with virustotal.
the windows defender is used by many people,
because they are too lazy or because it hardly makes sense to install another virus-scanner.

**Comment by vatterspun** [comment]
See issues #158 and this link http://www.nirsoft.net/false_positive_report.html for a little background.

> i will not stop using "Windows 10 defender 2004" 

False positives are probably a reality for the usage of this program and many actively developed programs on Github.  Also, because Microsoft is pushing their "store" model harder (where they make a lot more money), Windows defender will continue to identify non-store programs as malware.  

> i use UniExtract since years and i cannot live without it.*

You might consider using older versions of UniExtract that have been tested more.

> please fix your app or talk to the antivirus manufacturers.

You can assist by submitting the program for analysis and registering with.  But the truth is, anti-virus companies are not in the business of letting files in, but keeping them out.  It's time-consuming and expensive to test and verify software.  As UniExtract gains popularity and attention, it will be put higher on the list of software to test for issues.

**Comment by Bioruebe** [comment]
A while ago I created [a document about the whole virus problem](https://github.com/Bioruebe/UniExtract2/blob/master/docs/ANTI-MALWARE.md), because it's a very commonly reported issue for UniExtract.
To sum it up: I try my best to get it whitelisted, but it's a pain.
