### ISSUE TITLE
How to uninstall UniExtract2

### ISSUE THREAD

**Issue by cleanerspam** [Bioruebe/UniExtract2#244]
hi,
i cant find out how to remove this utility ,as this is a portable software It is providing no option to remove from control panel 
there is no details on uninstalling in _readme.md_ also
even deleting the folder from which it was installed does not seems to remove it 

**I want to remove the context entries as well as the files pasted/installed anywhere on PC**

**Comment by Bioruebe** [comment]
Hello and sorry for the confusion caused by the incomplete readme. I added uninstall instructions; this should make it clear for everyone, who wants to remove UniExtract.

A proper installer and uninstaller is planned for one of the next releases, which should make is way easier to set up and remove the program.

In short: Open UniExtract, click `Edit` > `Context Menu Entries`, uncheck the checkbox labeled `enabled` and click OK.

![Context menu](https://user-images.githubusercontent.com/3521951/104696372-793afe00-570e-11eb-82fb-2cb99c74bb24.png)
