### ISSUE TITLE
Update actually installs an older version of triddefs.trd

### ISSUE THREAD

**Issue by jvidalw** [Bioruebe/UniExtract2#293]
Hi!
Every once in a while Uniextract offers me to install an "update", but what it actually does is install AN OLDER version of Triddefs.trd.
I routinely update this file manually, so every time I'm offered this "update" I end up with an older vesion and I have to manually re-update it.
Can something be done about this?

**Comment by jvidalw** [comment]
well, anybody? like AT ALL?

**Comment by isaak654** [comment]
See https://github.com/Bioruebe/UniExtract2/issues/152#issue-438985665 :

> UniExtract uses custom definitions - do not update yourself!

**Comment by Bioruebe** [comment]
Exactly. At the moment, UniExtract uses modified versions of some extractors and definitions. That's why the updater replaces everything that does not match these, even newer versions - to discourage updating the files yourself. Because the modifications were specifically made to make the extractors work with UniExtract and updating them manually would result in bugs.

In the long term, updates to the program files should be automated to a degree, so that files like the triddefs are always up-to-date and no one needs to do that manually. But that's just not ready yet.

**Comment by jvidalw** [comment]
I'm gonna have to disagree. I routinely update the file manually and have never had an issue with it.

**Comment by Bioruebe** [comment]
I believe you, it's totally possible that you never encountered a file type that needs a modified version of triddefs. Most extractions will work perfectly, just a handful of files will fail when updating the definitions yourself.

**Comment by jvidalw** [comment]
plus, the version of triddef included with uniextract is severely outdated compared to the original version.
