### ISSUE TITLE
[FEATURE]Updater for internal bin and languages like "old" gora mod....

### ISSUE THREAD

**Issue by DjDiabolik** [Bioruebe/UniExtract2#32]
After gora has passed away (R.I.P.) i have tryed to found an alternative version like this........ i found this whit so many daily change and similar but i have tryed the "portable" beta3 and the actually updater if works only for main version and not for single files like gora mod right ?
It's possibly to develop somethings similar for maintain upgraded all bin extractor ??

**Comment by mikhoul** [comment]
I agree !   :+1:

**Comment by GitHubRulesOK** [comment]
Historically this has been a perpetual thorny issue since early versions

If the updates are "automatic" or downloaded in bundles it is very easy for numerous critics 
to complain their usage is now broken, this is most noticable by the dependancy on trid when marco "refines" his detectors (Gora and other forks attempt to avoid relying on vanilla trid as it often causes problems)

With many different forum users RU, USA etc etc it was difficult for gora to please ALL of the users ALL  of the time, I would suggest there would need to be a "restore" earlier version (similar to the "switch" between 7-zip versions

Gora (who often helped Jared/Nitro with updates)  also had issues later with alternative (pirate) versions using his reserch into updated components, I think that was a major factor that made him go closed source.
The answer is to ask users to "propose" updates on ONE forum (prefered if not requiring sign-in) or a Single GITHUB PAGE (where sign-in is required to avoid non constructive chatter)

another path is to allow users to install updates at their own risk same as plugins

**Comment by vatterspun** [comment]
> I think that was a major factor that made him go closed source

I had a conversation with Gora around his "decision" to take the program closed-source, which is against the terms of the license many Uniextract elements are released under.  His lack of awareness around the whole "share and share alike" concept was really annoying.  The whole point of the GPL was to get everything out in the open and then if you didn't like where the project was going, you could fork it.  Now Gora's good changes and ideas are gone.

Anyway, there are many open source programs that include automatic update functions.  The number and variety of Universal Extractor forks and variants admittedly make that harder but certainly not impossible.
