### ISSUE TITLE
What is the difference between UniExtract2 and the repack ones?

### ISSUE THREAD

**Issue by Unknown78** [Bioruebe/UniExtract2#98]
If you take a look at this link, there is the latest repack version that I've been found.
So what is the difference? Have both of the parties discuss together?

I think it would be better if there was a comparative description or table
https://www.wincert.net/forum/index.php?/files/file/43-universal-extractor-1921209b-by-goravandit/

**Comment by mikhoul** [comment]
The Gora fork was one of the best but now he is dead and this repo seem abandoned, there is no real communication from the author so I use this actively developed fork by a Russian developer: https://drive.google.com/drive/folders/1KfG8qP2mKyY2tfeK-FFDMuDA1fUrIhmn

For me it open lot more archives and it is more stable..

Regards :octocat:

**Comment by Unknown78** [comment]
Okay, after tracing the link you gave (using google translate lol). I've found the [homepage of it](http://forum.ru-board.com/topic.cgi?forum=5&topic=20420&glp)

You give me more dilemma, should I use UniExtract2 or that one

**Comment by RoyiAvital** [comment]
Does anyone work on this anymore?

**Comment by mikhoul** [comment]
@RoyiAvital  The "Russian" version is alive and updated regularly .

@Unknown78 You could use both since it's a portable software but on my side I use only "the Russian" version since UniExtract2 failed on many archives I was trying to extract were the "Russian" version was successful. 

Regards :octocat:

**Comment by Bioruebe** [comment]
When the original developer of UE stopped working on it, many people from around the world continued to update and improve UniExtract. Some 'only' updated the different dependencies (extractors), others added great features. My fork - as well as the most popular version created by Gora - are from the latter category. As Gora passed away a while ago, new developers continued his work and basically that's why there are a ton of differently named UniExtracts.

Regarding features, all versions are based on the same source. How they work and look is almost the same for all versions. However, different developers focus on different aspects. UE2 has batch mode, auto-update and can cope with video files and some game archives; the forks linked in this issue are apparently better at 'many archives'. Maybe @mikhoul can give more information on what kind of files tend to fail most here? I'm alwasy trying to improve my software, so your feedback would be really helpful :)

At the moment there is no collaboration between the russian developers and me. I'm not against it; it would be great to have a 'perfect' UniExtract with all the features currently scattered throughout different versions; and from what I read, the russian UE community has some pretty capable devs.

Which version you should use depends on what files you want to extract. I suggest using one main version and try others only if it fails. Simply test some UniExtracts and use what's working best for you. As already said in this thread, the software is portable and multiple versions can be used without problems.

---
> The Gora fork was one of the best but now he is dead and this repo here seem abandoned, there is no real communication from the author.

If you call regular commits abandonned, then you should never try to search javascript libraries on Github. You would be happy about even one commit per year ;)
But seriously, my apologies if you find my communication lacking. I read all the issues and comments and try to answer them whenever possible, but support is always the most time-consuming part of software maintenance. Most developers like to focus on actually developing and quite a few even had to abandon projects because the time needed to answer user's emails became too much.
I try to do my best while keeping a bit of free time for other things, but don't hesistate to tell me which aspects I should communicate more extensive.

Btw, I got some help with the final QA testing today and found the last (hopefully) bugs left in the update mechanism. You can expect a new version to be released withing the next days. 🎉

**Comment by Bioruebe** [comment]
Oh, sorry. Seems like I misunderstood. I thought you were refering to whole file types not being supported (e.g. UE2 cannot extract .asar archives, while the Russian version can). That's why I asked for more information.

The log files normally contain enough information (or I simply search for the file online and try it myself), I even removed the email input because of that. However, a lot of the feedback is related to a specific file. If many people report broken extraction and all of them being inno installers, I can search for updates of the unpacker or check UniExtract's code. But if an installer for a specific program cannot be decompressed and the detectors are not able to find the signature of one of the big installation systems, that's more difficult and can take a long time or may not be worth being fixed at all.
I don't know if that's the case for all of your feedback. It's more likely that the lack of updates in general lead to the impression of me ignoring bug reports. Let me explain a bit more:

The reason for the whole no-update problem is that after Beta 4 I realized how inefficient the current updater worked. Actually, it's the opposite of spending a few minutes uploading a file to Github. UE2 used an archive based approach: it downloaded the update package (basically a zip file, to keep the server load and update size low) and extracted it, replacing the old files. For me that meant creating a ton of different archives: one for the last version, one for older ones, a full release version for Github. Then I had to upload them, test each one, and change the scripts to make it public. Doing that for a single updated compressor like 7z became a heavy and unneccessary load. I previously tried to simplify it by using scripts to create the packages, but it still wasn't feasible...
That's why I decided to delay further releases until an efficient system has been established. Better to do that while in Beta, as users might expect problems and probably forgive me :)
Additionally, overwriting files sometimes was even worse and requirent rather ugly workarounds. E.g. your example: 7zip was used to extract the update packages, meaning it cannot overwrite itself and the files have to be renamed. Don't get me wrong, I don't want to complain how hard developing UE is. I just noticed that I could not continue like that and had to change one of the most critical parts of the software. But with a work-in-progress updater, even some minor modification like a security update was a risk, which could destroy thousands of installations of UE2.
With the new updater releasing minor updates is reduced to uploading a file and hitting 'refresh' to make it go live.

I know, what you want to answer: I should have written this explanation way earlier to keep the community up-to-date. You are completely right. I know that now, and the next time something like that happens I will do it.

However, thanks for explaining your point of view. I try to be a bit more communicative in the future.
Also a special thanks to the community, who kept replying to issues, helped answer user questions and even compiled new versions when I was away ❤️

**Comment by mikhoul** [comment]
Just a little bit more communication and it will be lot more easy to follow the development for everybody.

For myself I don't mind if the update are not automatic since I use https://gitpunch.com/ and receive an email everytime a new version of the project I like is released.

Just having a basic version even is it don't auto-update would be fine.

Again I understand it take lot of time to maintain a project but just answering quickly to the issue once a month will be fine or even just acknowledging you have read the issue.

And you're right I was under the impression that the report I was sending were going in a black hole somewhere in the cyberspace...✨⭐️✨ 😜

Thanks for your honest answer also with Russian it is hard to work with them when they use 4PDA forum since only Russian is allowed on 4PDA so many time I have to use Google Translate to communicate with them since they have lot of knowledge on 4PDA forum.

Have a nice day ! 😊  :octocat:

**Comment by Bioruebe** [comment]
Gitpunch looks like a neat service, didn't knew about it before. Could be useful for keeping track of the latest versions of some of the extractors.

> Just having a basic version even is it don't auto-update would be fine.

I don't think that's very user-friendly. Most people wouldn't bother with checking for new versions manually. But who cares, UE has its new updating mechanism, so everything is fine 😃

> just answering quickly to the issue once a month will be fine or even just acknowledging you have read the issue.

I'll try.

Have a nice day, too.

**Comment by Unknown78** [comment]
Hmm, I've actually silently read, I'm a newcomer, can't help much, but I hope my question above bring down a peace upon all of you

I have an advice to lessen the human resource problem. Make it easier for the people who have programming skill to interest in developing this project.

It'll be nice to have an automated nightly build, it is not for daily usage, but for just developing only. Reading the instructions and compile it may be a lazy task depending on the person. My point is that some people may be impatience and want to run it quickly, and see what he can improve.

CI will be appropriate in this case, just use an open-source Jenkins which is free, or anything else that you like.

One more thing, scattered development is bad. The Russian version can extract the ones that this version can't, has a legacy UI, a little settings improvement. And this one also can extract the ones that the Russian can't, such as audio and video, more feature and settings. It's not like comparing Kali and Ubuntu which obviously has a significant different main purpose. Both of these version has the same main purpose, create program that can extract anything, U-N-I-V-E-R-S-A-L. Seriously, at this point, only the user has the worst disadvantage. Yes, installing both version may get the job well done, but it's not just practical. 

I do really hope both of you and the Russian dev work together.

**Comment by Bioruebe** [comment]
Thanks for your feedback. I just added a nightly channel to the updater, so everyone who's interested in testing the current dev version can just set an option and automatically get the newest build. (This feature will go live with the next regular update)
There's no CI yet, I'm not sure if it would work well for UniExtract. Many changes to the code require updating or adding helper files as well. This means the rebuilt main executable alone might have a new feature, but it doesn't work because of missing files. I might look into CI in the future, but at the moment I think I will stick with a manual upload. I need to compile new builds anyway (for my own tests), so simply uploading them to the nightly branch whenaver I changed something takes no time.

**Comment by rmenessec** [comment]
@Bioruebe, have you considered updating the project description, preferably near the top? If there's a big, official message from you, clearly visible to visitors, explaining why there are no new releases and warning everyone to expect—let's say "slow response to issues due to my current workload"—that would go a long way toward setting expectations, and these threads wouldn't happen (as often).

When I see that a GitHub project owner has gone a long time without responding to issues and there's no official word about what I should expect, it does in fact look like the project's abandoned, even if there are current commits. For all I know, the commits are coming from an automatic batch job of some kind that's mirroring to GitHub, and the project owner (or GitHub admin) has forgotten that the GitHub side exists.

It's not uncommon to see projects with a sole developer experience apparent abandonment after some end user-invisible change, like an unannounced migration from GitHub as primary development locus to GitLab or a private Git instance plus a website I don't know about. Sometimes the primary communication channel is a sub-page hosted by a larger project; a forum thread somewhere; or even an obscure IRC / Discord / _etc._ resource that I might never in a million years find on my own.

If there isn't regular communication via the GitHub project description, I have to dig into the issues to see if anyone knows where the developer went. If there are hundreds of issues, and nothing open and recent / pinned with a clear reference to project status, I give up instantly; I don't have the time to check every open and closed issue for a random mention of what's going on.

**Comment by Bioruebe** [comment]
Good suggestion. At the moment I'm working on UE and responding, but I'll try to remember adding a warning to the readme if there are more major slowdowns in the future.
